// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file services/gps/gps.proto (package gps, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "../../base/empty_pb";
import { file_base_empty } from "../../base/empty_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file services/gps/gps.proto.
 */
export const file_services_gps_gps: GenFile = /*@__PURE__*/
  fileDesc("ChZzZXJ2aWNlcy9ncHMvZ3BzLnByb3RvEgNncHMifQoPR2V0R3BzRGF0YVJlcGx5EhMKC2lzQ29ubmVjdGVkGAEgASgIEg8KB2lzUmVhZHkYAiABKAgSEAoIbGF0aXR1ZGUYAyABKAkSEQoJbG9uZ2l0dWRlGAQgASgJEg4KBnN0YXR1cxgFIAEoCRIPCgdncHNUeXBlGAYgASgJMj8KCkdwc1NlcnZpY2USMQoKR2V0R3BzRGF0YRILLmJhc2UuRW1wdHkaFC5ncHMuR2V0R3BzRGF0YVJlcGx5IgBCnwEKB2NvbS5ncHNCCEdwc1Byb3RvUAFaXmdpdGh1Yi5jb20vaGFja2h1bnRlcmRldi9waS1zZW5zb3JzL3B1cnN1aXQtYW5kLXNvbG8vcHJvdG8tZGVmaW5pdGlvbnMvX2dlbmVyYXRlZC9zZXJ2aWNlcy9ncHOiAgNHWFiqAgNHcHPKAgNHcHPiAg9HcHNcR1BCTWV0YWRhdGHqAgNHcHNiBnByb3RvMw", [file_base_empty]);

/**
 * @generated from message gps.GetGpsDataReply
 */
export type GetGpsDataReply = Message<"gps.GetGpsDataReply"> & {
  /**
   * @generated from field: bool isConnected = 1;
   */
  isConnected: boolean;

  /**
   * @generated from field: bool isReady = 2;
   */
  isReady: boolean;

  /**
   * @generated from field: string latitude = 3;
   */
  latitude: string;

  /**
   * @generated from field: string longitude = 4;
   */
  longitude: string;

  /**
   * @generated from field: string status = 5;
   */
  status: string;

  /**
   * @generated from field: string gpsType = 6;
   */
  gpsType: string;
};

/**
 * Describes the message gps.GetGpsDataReply.
 * Use `create(GetGpsDataReplySchema)` to create a new message.
 */
export const GetGpsDataReplySchema: GenMessage<GetGpsDataReply> = /*@__PURE__*/
  messageDesc(file_services_gps_gps, 0);

/**
 * @generated from service gps.GpsService
 */
export const GpsService: GenService<{
  /**
   * @generated from rpc gps.GpsService.GetGpsData
   */
  getGpsData: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof GetGpsDataReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_services_gps_gps, 0);

