// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file services/rssi/rssi.proto (package rssi, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_base_traffic } from "../../base/traffic_pb";
import { file_base_devices } from "../../base/devices_pb";
import { file_base_comms } from "../../base/comms_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file services/rssi/rssi.proto.
 */
export const file_services_rssi_rssi: GenFile = /*@__PURE__*/
  fileDesc("ChhzZXJ2aWNlcy9yc3NpL3Jzc2kucHJvdG8SBHJzc2kiUwocU3RhcnRSc3NpU3RyZWFtRm9yTWFjUmVxdWVzdBILCgNtYWMYASABKAkSFwoKdGhyb3R0bGVNcxgCIAEoDUgAiAEBQg0KC190aHJvdHRsZU1zIhQKBFJzc2kSDAoEcnNzaRgBIAEoBTJaCgtSc3NpU2VydmljZRJLChVTdGFydFJzc2lTdHJlYW1Gb3JNYWMSIi5yc3NpLlN0YXJ0UnNzaVN0cmVhbUZvck1hY1JlcXVlc3QaCi5yc3NpLlJzc2kiADABQqYBCghjb20ucnNzaUIJUnNzaVByb3RvUAFaX2dpdGh1Yi5jb20vaGFja2h1bnRlcmRldi9waS1zZW5zb3JzL3B1cnN1aXQtYW5kLXNvbG8vcHJvdG8tZGVmaW5pdGlvbnMvX2dlbmVyYXRlZC9zZXJ2aWNlcy9yc3NpogIDUlhYqgIEUnNzacoCBFJzc2niAhBSc3NpXEdQQk1ldGFkYXRh6gIEUnNzaWIGcHJvdG8z", [file_base_traffic, file_base_devices, file_base_comms]);

/**
 * @generated from message rssi.StartRssiStreamForMacRequest
 */
export type StartRssiStreamForMacRequest = Message<"rssi.StartRssiStreamForMacRequest"> & {
  /**
   * @generated from field: string mac = 1;
   */
  mac: string;

  /**
   * @generated from field: optional uint32 throttleMs = 2;
   */
  throttleMs?: number;
};

/**
 * Describes the message rssi.StartRssiStreamForMacRequest.
 * Use `create(StartRssiStreamForMacRequestSchema)` to create a new message.
 */
export const StartRssiStreamForMacRequestSchema: GenMessage<StartRssiStreamForMacRequest> = /*@__PURE__*/
  messageDesc(file_services_rssi_rssi, 0);

/**
 * @generated from message rssi.Rssi
 */
export type Rssi = Message<"rssi.Rssi"> & {
  /**
   * @generated from field: int32 rssi = 1;
   */
  rssi: number;
};

/**
 * Describes the message rssi.Rssi.
 * Use `create(RssiSchema)` to create a new message.
 */
export const RssiSchema: GenMessage<Rssi> = /*@__PURE__*/
  messageDesc(file_services_rssi_rssi, 1);

/**
 * @generated from service rssi.RssiService
 */
export const RssiService: GenService<{
  /**
   * @generated from rpc rssi.RssiService.StartRssiStreamForMac
   */
  startRssiStreamForMac: {
    methodKind: "server_streaming";
    input: typeof StartRssiStreamForMacRequestSchema;
    output: typeof RssiSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_services_rssi_rssi, 0);

