// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file base/comms.proto (package base, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file base/comms.proto.
 */
export const file_base_comms: GenFile = /*@__PURE__*/
  fileDesc("ChBiYXNlL2NvbW1zLnByb3RvEgRiYXNlIpcBCg5BcENvbW1zSGlzdG9yeRI0CghzcmNEZXN0cxgBIAMoCzIiLmJhc2UuQXBDb21tc0hpc3RvcnkuU3JjRGVzdHNFbnRyeRpPCg1TcmNEZXN0c0VudHJ5EgsKA2tleRgBIAEoCRItCgV2YWx1ZRgCIAEoCzIeLmJhc2UuQ29tbXNIaXN0b3J5U3JjRGVzdEVudHJ5OgI4ASKgAQoTU3RhdGlvbkNvbW1zSGlzdG9yeRI1CgZic3NpZHMYASADKAsyJS5iYXNlLlN0YXRpb25Db21tc0hpc3RvcnkuQnNzaWRzRW50cnkaUgoLQnNzaWRzRW50cnkSCwoDa2V5GAEgASgJEjIKBXZhbHVlGAIgASgLMiMuYmFzZS5TdGF0aW9uQ29tbXNIaXN0b3J5QnNzaWRFbnRyeToCOAEi3QEKHVN0YXRpb25Db21tc0hpc3RvcnlCc3NpZEVudHJ5EhIKCmxhc3RTZWVuTXMYASABKAQSEgoKdG90YWxDb3VudBgCIAEoDRJDCghzcmNEZXN0cxgDIAMoCzIxLmJhc2UuU3RhdGlvbkNvbW1zSGlzdG9yeUJzc2lkRW50cnkuU3JjRGVzdHNFbnRyeRpPCg1TcmNEZXN0c0VudHJ5EgsKA2tleRgBIAEoCRItCgV2YWx1ZRgCIAEoCzIeLmJhc2UuQ29tbXNIaXN0b3J5U3JjRGVzdEVudHJ5OgI4ASLXAQoYQ29tbXNIaXN0b3J5U3JjRGVzdEVudHJ5EhIKCmxhc3RTZWVuTXMYASABKAQSEgoKdG90YWxDb3VudBgCIAEoDRJCCgpmcmFtZVR5cGVzGAMgAygLMi4uYmFzZS5Db21tc0hpc3RvcnlTcmNEZXN0RW50cnkuRnJhbWVUeXBlc0VudHJ5Gk8KD0ZyYW1lVHlwZXNFbnRyeRILCgNrZXkYASABKA0SKwoFdmFsdWUYAiABKAsyHC5iYXNlLkNvbW1zSGlzdG9yeUZyYW1lVHlwZXM6AjgBIqoBChZDb21tc0hpc3RvcnlGcmFtZVR5cGVzEhIKCnRvdGFsQ291bnQYASABKA0SRgoNc3VidHlwZUNvdW50cxgCIAMoCzIvLmJhc2UuQ29tbXNIaXN0b3J5RnJhbWVUeXBlcy5TdWJ0eXBlQ291bnRzRW50cnkaNAoSU3VidHlwZUNvdW50c0VudHJ5EgsKA2tleRgBIAEoDRINCgV2YWx1ZRgCIAEoDToCOAFCngEKCGNvbS5iYXNlQgpDb21tc1Byb3RvUAFaVmdpdGh1Yi5jb20vaGFja2h1bnRlcmRldi9waS1zZW5zb3JzL3B1cnN1aXQtYW5kLXNvbG8vcHJvdG8tZGVmaW5pdGlvbnMvX2dlbmVyYXRlZC9iYXNlogIDQlhYqgIEQmFzZcoCBEJhc2XiAhBCYXNlXEdQQk1ldGFkYXRh6gIEQmFzZWIGcHJvdG8z");

/**
 * @generated from message base.ApCommsHistory
 */
export type ApCommsHistory = Message<"base.ApCommsHistory"> & {
  /**
   * map of "src_dest" key
   *
   * @generated from field: map<string, base.CommsHistorySrcDestEntry> srcDests = 1;
   */
  srcDests: { [key: string]: CommsHistorySrcDestEntry };
};

/**
 * Describes the message base.ApCommsHistory.
 * Use `create(ApCommsHistorySchema)` to create a new message.
 */
export const ApCommsHistorySchema: GenMessage<ApCommsHistory> = /*@__PURE__*/
  messageDesc(file_base_comms, 0);

/**
 * @generated from message base.StationCommsHistory
 */
export type StationCommsHistory = Message<"base.StationCommsHistory"> & {
  /**
   * map of "bssid" key
   *
   * @generated from field: map<string, base.StationCommsHistoryBssidEntry> bssids = 1;
   */
  bssids: { [key: string]: StationCommsHistoryBssidEntry };
};

/**
 * Describes the message base.StationCommsHistory.
 * Use `create(StationCommsHistorySchema)` to create a new message.
 */
export const StationCommsHistorySchema: GenMessage<StationCommsHistory> = /*@__PURE__*/
  messageDesc(file_base_comms, 1);

/**
 * @generated from message base.StationCommsHistoryBssidEntry
 */
export type StationCommsHistoryBssidEntry = Message<"base.StationCommsHistoryBssidEntry"> & {
  /**
   * @generated from field: uint64 lastSeenMs = 1;
   */
  lastSeenMs: bigint;

  /**
   * @generated from field: uint32 totalCount = 2;
   */
  totalCount: number;

  /**
   * map of "src_dest" key
   *
   * @generated from field: map<string, base.CommsHistorySrcDestEntry> srcDests = 3;
   */
  srcDests: { [key: string]: CommsHistorySrcDestEntry };
};

/**
 * Describes the message base.StationCommsHistoryBssidEntry.
 * Use `create(StationCommsHistoryBssidEntrySchema)` to create a new message.
 */
export const StationCommsHistoryBssidEntrySchema: GenMessage<StationCommsHistoryBssidEntry> = /*@__PURE__*/
  messageDesc(file_base_comms, 2);

/**
 * @generated from message base.CommsHistorySrcDestEntry
 */
export type CommsHistorySrcDestEntry = Message<"base.CommsHistorySrcDestEntry"> & {
  /**
   * @generated from field: uint64 lastSeenMs = 1;
   */
  lastSeenMs: bigint;

  /**
   * @generated from field: uint32 totalCount = 2;
   */
  totalCount: number;

  /**
   * @generated from field: map<uint32, base.CommsHistoryFrameTypes> frameTypes = 3;
   */
  frameTypes: { [key: number]: CommsHistoryFrameTypes };
};

/**
 * Describes the message base.CommsHistorySrcDestEntry.
 * Use `create(CommsHistorySrcDestEntrySchema)` to create a new message.
 */
export const CommsHistorySrcDestEntrySchema: GenMessage<CommsHistorySrcDestEntry> = /*@__PURE__*/
  messageDesc(file_base_comms, 3);

/**
 * @generated from message base.CommsHistoryFrameTypes
 */
export type CommsHistoryFrameTypes = Message<"base.CommsHistoryFrameTypes"> & {
  /**
   * @generated from field: uint32 totalCount = 1;
   */
  totalCount: number;

  /**
   * @generated from field: map<uint32, uint32> subtypeCounts = 2;
   */
  subtypeCounts: { [key: number]: number };
};

/**
 * Describes the message base.CommsHistoryFrameTypes.
 * Use `create(CommsHistoryFrameTypesSchema)` to create a new message.
 */
export const CommsHistoryFrameTypesSchema: GenMessage<CommsHistoryFrameTypes> = /*@__PURE__*/
  messageDesc(file_base_comms, 4);

