// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file base/connection.proto (package base, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file base/connection.proto.
 */
export const file_base_connection: GenFile = /*@__PURE__*/
  fileDesc("ChViYXNlL2Nvbm5lY3Rpb24ucHJvdG8SBGJhc2UixQEKE0FwQ29ubmVjdGlvbkRldGFpbHMSHgoWY291bnRDb25uZWN0ZWRTdGF0aW9ucxgBIAEoDRJRChRjb25uZWN0ZWRTdGF0aW9uTWFjcxgCIAMoCzIzLmJhc2UuQXBDb25uZWN0aW9uRGV0YWlscy5Db25uZWN0ZWRTdGF0aW9uTWFjc0VudHJ5GjsKGUNvbm5lY3RlZFN0YXRpb25NYWNzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgIOgI4ASL3AwoYU3RhdGlvbkNvbm5lY3Rpb25EZXRhaWxzEhMKC2lzQ29ubmVjdGVkGAEgASgIEicKB2NoYW5uZWwYDSABKAsyES5iYXNlLkNoYW5uZWxJbmZvSACIAQESHAoPY29ubmVjdGVkVG9Tc2lkGA4gASgJSAGIAQESHQoQY29ubmVjdGVkVG9Cc3NpZBgPIAEoCUgCiAEBEiEKFGNvbm5lY3RlZFRvVmlydHVhbEFwGBAgASgISAOIAQESMwoMb3B0aW1pc2VkRm9yGBEgASgOMhguYmFzZS5EZXZpY2VPcHRpbWlzYXRpb25IBIgBARJQChFjb25uZWN0aW9uSGlzdG9yeRgSIAMoCzI1LmJhc2UuU3RhdGlvbkNvbm5lY3Rpb25EZXRhaWxzLkNvbm5lY3Rpb25IaXN0b3J5RW50cnkaVwoWQ29ubmVjdGlvbkhpc3RvcnlFbnRyeRILCgNrZXkYASABKAkSLAoFdmFsdWUYAiABKAsyHS5iYXNlLlN0YXRpb25Db25uZWN0aW9uUmVjb3JkOgI4AUIKCghfY2hhbm5lbEISChBfY29ubmVjdGVkVG9Tc2lkQhMKEV9jb25uZWN0ZWRUb0Jzc2lkQhcKFV9jb25uZWN0ZWRUb1ZpcnR1YWxBcEIPCg1fb3B0aW1pc2VkRm9yIngKC0NoYW5uZWxJbmZvEigKBGJhbmQYASABKA4yGi5iYXNlLkNoYW5uZWxGcmVxdWVuY3lCYW5kEg8KB2NoYW5uZWwYAiABKAUSDAoEZnJlcRgDIAEoBRIPCgdmcmVxTWluGAQgASgFEg8KB2ZyZXFNYXgYBSABKAUiVAoXU3RhdGlvbkNvbm5lY3Rpb25SZWNvcmQSHAoUdGltZUZpcnN0Q29ubmVjdGVkQXQYASABKAQSGwoTdGltZUxhc3RDb25uZWN0ZWRBdBgCIAEoBCo5ChRDaGFubmVsRnJlcXVlbmN5QmFuZBILCgdHSFpfMl80EAASCQoFR0haXzUQARIJCgVHSFpfNhACKksKEkRldmljZU9wdGltaXNhdGlvbhIPCgtCRVNUX0VGRk9SVBAAEg4KCkJBQ0tHUk9VTkQQARIJCgVWSURFTxACEgkKBVZPSUNFEANCowEKCGNvbS5iYXNlQg9Db25uZWN0aW9uUHJvdG9QAVpWZ2l0aHViLmNvbS9oYWNraHVudGVyZGV2L3BpLXNlbnNvcnMvcHVyc3VpdC1hbmQtc29sby9wcm90by1kZWZpbml0aW9ucy9fZ2VuZXJhdGVkL2Jhc2WiAgNCWFiqAgRCYXNlygIEQmFzZeICEEJhc2VcR1BCTWV0YWRhdGHqAgRCYXNlYgZwcm90bzM");

/**
 * @generated from message base.ApConnectionDetails
 */
export type ApConnectionDetails = Message<"base.ApConnectionDetails"> & {
  /**
   * @generated from field: uint32 countConnectedStations = 1;
   */
  countConnectedStations: number;

  /**
   * @generated from field: map<string, bool> connectedStationMacs = 2;
   */
  connectedStationMacs: { [key: string]: boolean };
};

/**
 * Describes the message base.ApConnectionDetails.
 * Use `create(ApConnectionDetailsSchema)` to create a new message.
 */
export const ApConnectionDetailsSchema: GenMessage<ApConnectionDetails> = /*@__PURE__*/
  messageDesc(file_base_connection, 0);

/**
 * @generated from message base.StationConnectionDetails
 */
export type StationConnectionDetails = Message<"base.StationConnectionDetails"> & {
  /**
   * @generated from field: bool isConnected = 1;
   */
  isConnected: boolean;

  /**
   * @generated from field: optional base.ChannelInfo channel = 13;
   */
  channel?: ChannelInfo;

  /**
   * @generated from field: optional string connectedToSsid = 14;
   */
  connectedToSsid?: string;

  /**
   * @generated from field: optional string connectedToBssid = 15;
   */
  connectedToBssid?: string;

  /**
   * @generated from field: optional bool connectedToVirtualAp = 16;
   */
  connectedToVirtualAp?: boolean;

  /**
   * @generated from field: optional base.DeviceOptimisation optimisedFor = 17;
   */
  optimisedFor?: DeviceOptimisation;

  /**
   * @generated from field: map<string, base.StationConnectionRecord> connectionHistory = 18;
   */
  connectionHistory: { [key: string]: StationConnectionRecord };
};

/**
 * Describes the message base.StationConnectionDetails.
 * Use `create(StationConnectionDetailsSchema)` to create a new message.
 */
export const StationConnectionDetailsSchema: GenMessage<StationConnectionDetails> = /*@__PURE__*/
  messageDesc(file_base_connection, 1);

/**
 * @generated from message base.ChannelInfo
 */
export type ChannelInfo = Message<"base.ChannelInfo"> & {
  /**
   * @generated from field: base.ChannelFrequencyBand band = 1;
   */
  band: ChannelFrequencyBand;

  /**
   * @generated from field: int32 channel = 2;
   */
  channel: number;

  /**
   * @generated from field: int32 freq = 3;
   */
  freq: number;

  /**
   * @generated from field: int32 freqMin = 4;
   */
  freqMin: number;

  /**
   * @generated from field: int32 freqMax = 5;
   */
  freqMax: number;
};

/**
 * Describes the message base.ChannelInfo.
 * Use `create(ChannelInfoSchema)` to create a new message.
 */
export const ChannelInfoSchema: GenMessage<ChannelInfo> = /*@__PURE__*/
  messageDesc(file_base_connection, 2);

/**
 * @generated from message base.StationConnectionRecord
 */
export type StationConnectionRecord = Message<"base.StationConnectionRecord"> & {
  /**
   * @generated from field: uint64 timeFirstConnectedAt = 1;
   */
  timeFirstConnectedAt: bigint;

  /**
   * @generated from field: uint64 timeLastConnectedAt = 2;
   */
  timeLastConnectedAt: bigint;
};

/**
 * Describes the message base.StationConnectionRecord.
 * Use `create(StationConnectionRecordSchema)` to create a new message.
 */
export const StationConnectionRecordSchema: GenMessage<StationConnectionRecord> = /*@__PURE__*/
  messageDesc(file_base_connection, 3);

/**
 * @generated from enum base.ChannelFrequencyBand
 */
export enum ChannelFrequencyBand {
  /**
   * @generated from enum value: GHZ_2_4 = 0;
   */
  GHZ_2_4 = 0,

  /**
   * @generated from enum value: GHZ_5 = 1;
   */
  GHZ_5 = 1,

  /**
   * @generated from enum value: GHZ_6 = 2;
   */
  GHZ_6 = 2,
}

/**
 * Describes the enum base.ChannelFrequencyBand.
 */
export const ChannelFrequencyBandSchema: GenEnum<ChannelFrequencyBand> = /*@__PURE__*/
  enumDesc(file_base_connection, 0);

/**
 * @generated from enum base.DeviceOptimisation
 */
export enum DeviceOptimisation {
  /**
   * @generated from enum value: BEST_EFFORT = 0;
   */
  BEST_EFFORT = 0,

  /**
   * @generated from enum value: BACKGROUND = 1;
   */
  BACKGROUND = 1,

  /**
   * @generated from enum value: VIDEO = 2;
   */
  VIDEO = 2,

  /**
   * @generated from enum value: VOICE = 3;
   */
  VOICE = 3,
}

/**
 * Describes the enum base.DeviceOptimisation.
 */
export const DeviceOptimisationSchema: GenEnum<DeviceOptimisation> = /*@__PURE__*/
  enumDesc(file_base_connection, 1);

