// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file base/deauth.proto (package base, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file base/deauth.proto.
 */
export const file_base_deauth: GenFile = /*@__PURE__*/
  fileDesc("ChFiYXNlL2RlYXV0aC5wcm90bxIEYmFzZSJrCg9BcERlYXV0aERldGFpbHMSKAoMaXNEZWF1dGhhYmxlGAEgASgOMhIuYmFzZS5Jc0RlYXV0aGFibGUSEwoLaXNEZWF1dGhpbmcYAiABKAgSGQoRaGFzRGVhdXRoaW5nQ2hpbGQYAyABKAgifQoTU3RhdGlvbkRlYXV0aFJlc3VsdBINCgVic3NpZBgBIAEoCRIXCg9sYXN0VXBkYXRlZEF0TXMYAiABKAUSEwoLcmVhdXRoQ291bnQYAyABKAUSEQoJZGF0YUNvdW50GAQgASgFEhYKDmluamVjdGlvbkNvdW50GAUgASgFIocBChRTdGF0aW9uRGVhdXRoRGV0YWlscxIoCgxpc0RlYXV0aGFibGUYASABKA4yEi5iYXNlLklzRGVhdXRoYWJsZRITCgtpc0RlYXV0aGluZxgCIAEoCBIwCg1kZWF1dGhSZXN1bHRzGAMgAygLMhkuYmFzZS5TdGF0aW9uRGVhdXRoUmVzdWx0KjAKDElzRGVhdXRoYWJsZRIGCgJOTxAAEg8KC1BPVEVOVElBTExZEAESBwoDWUVTEAJCnwEKCGNvbS5iYXNlQgtEZWF1dGhQcm90b1ABWlZnaXRodWIuY29tL2hhY2todW50ZXJkZXYvcGktc2Vuc29ycy9wdXJzdWl0LWFuZC1zb2xvL3Byb3RvLWRlZmluaXRpb25zL19nZW5lcmF0ZWQvYmFzZaICA0JYWKoCBEJhc2XKAgRCYXNl4gIQQmFzZVxHUEJNZXRhZGF0YeoCBEJhc2ViBnByb3RvMw");

/**
 * @generated from message base.ApDeauthDetails
 */
export type ApDeauthDetails = Message<"base.ApDeauthDetails"> & {
  /**
   * @generated from field: base.IsDeauthable isDeauthable = 1;
   */
  isDeauthable: IsDeauthable;

  /**
   * @generated from field: bool isDeauthing = 2;
   */
  isDeauthing: boolean;

  /**
   * @generated from field: bool hasDeauthingChild = 3;
   */
  hasDeauthingChild: boolean;
};

/**
 * Describes the message base.ApDeauthDetails.
 * Use `create(ApDeauthDetailsSchema)` to create a new message.
 */
export const ApDeauthDetailsSchema: GenMessage<ApDeauthDetails> = /*@__PURE__*/
  messageDesc(file_base_deauth, 0);

/**
 * @generated from message base.StationDeauthResult
 */
export type StationDeauthResult = Message<"base.StationDeauthResult"> & {
  /**
   * @generated from field: string bssid = 1;
   */
  bssid: string;

  /**
   * @generated from field: int32 lastUpdatedAtMs = 2;
   */
  lastUpdatedAtMs: number;

  /**
   * @generated from field: int32 reauthCount = 3;
   */
  reauthCount: number;

  /**
   * @generated from field: int32 dataCount = 4;
   */
  dataCount: number;

  /**
   * @generated from field: int32 injectionCount = 5;
   */
  injectionCount: number;
};

/**
 * Describes the message base.StationDeauthResult.
 * Use `create(StationDeauthResultSchema)` to create a new message.
 */
export const StationDeauthResultSchema: GenMessage<StationDeauthResult> = /*@__PURE__*/
  messageDesc(file_base_deauth, 1);

/**
 * @generated from message base.StationDeauthDetails
 */
export type StationDeauthDetails = Message<"base.StationDeauthDetails"> & {
  /**
   * @generated from field: base.IsDeauthable isDeauthable = 1;
   */
  isDeauthable: IsDeauthable;

  /**
   * @generated from field: bool isDeauthing = 2;
   */
  isDeauthing: boolean;

  /**
   * @generated from field: repeated base.StationDeauthResult deauthResults = 3;
   */
  deauthResults: StationDeauthResult[];
};

/**
 * Describes the message base.StationDeauthDetails.
 * Use `create(StationDeauthDetailsSchema)` to create a new message.
 */
export const StationDeauthDetailsSchema: GenMessage<StationDeauthDetails> = /*@__PURE__*/
  messageDesc(file_base_deauth, 2);

/**
 * @generated from enum base.IsDeauthable
 */
export enum IsDeauthable {
  /**
   * @generated from enum value: NO = 0;
   */
  NO = 0,

  /**
   * @generated from enum value: POTENTIALLY = 1;
   */
  POTENTIALLY = 1,

  /**
   * @generated from enum value: YES = 2;
   */
  YES = 2,
}

/**
 * Describes the enum base.IsDeauthable.
 */
export const IsDeauthableSchema: GenEnum<IsDeauthable> = /*@__PURE__*/
  enumDesc(file_base_deauth, 0);

