// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file base/devices.proto (package base, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Identity } from "./identity_pb";
import { file_base_identity } from "./identity_pb";
import { file_base_auth } from "./auth_pb";
import { file_base_lists } from "./lists_pb";
import type { ChannelInfo } from "./connection_pb";
import { file_base_connection } from "./connection_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file base/devices.proto.
 */
export const file_base_devices: GenFile = /*@__PURE__*/
  fileDesc("ChJiYXNlL2RldmljZXMucHJvdG8SBGJhc2UingQKBkJhc2VBcBIMCgRhcElkGAEgASgJEg0KBWJzc2lkGAIgASgJEhMKC2ZpbmdlcnByaW50GAMgASgJEhwKFGxvd2VzdEF1dGhlbnRpY2F0aW9uGAQgASgJEiMKG2FsbFN1cHBvcnRlZEF1dGhlbnRpY2F0aW9ucxgFIAMoCRIfChJzZWN1cml0eUV2YWx1YXRpb24YByABKAlIAIgBARIZCgxpc1dpZmlEaXJlY3QYCCABKAhIAYgBARIiCgdjaGFubmVsGAogASgLMhEuYmFzZS5DaGFubmVsSW5mbxIRCgRzc2lkGAsgASgJSAKIAQESEgoFaXNXUFMYDCABKAhIA4gBARIRCgRpc05QGA0gASgISASIAQESFwoKcG1mQ2FwYWJsZRgOIAEoCEgFiAEBEhgKC3BtZlJlcXVpcmVkGA8gASgISAaIAQESEwoLZmlyc3RTZWVuTXMYECABKAMSEgoKbGFzdFNlZW5NcxgRIAEoAxISCgp2ZW5kb3JUYWdzGBUgAygJEiUKCGlkZW50aXR5GBYgASgLMg4uYmFzZS5JZGVudGl0eUgHiAEBQhUKE19zZWN1cml0eUV2YWx1YXRpb25CDwoNX2lzV2lmaURpcmVjdEIHCgVfc3NpZEIICgZfaXNXUFNCBwoFX2lzTlBCDQoLX3BtZkNhcGFibGVCDgoMX3BtZlJlcXVpcmVkQgsKCV9pZGVudGl0eSKwAgoLQmFzZVN0YXRpb24SCwoDbWFjGAEgASgJEhIKBWFsaWFzGAIgASgJSACIAQESHwoSc2VjdXJpdHlFdmFsdWF0aW9uGAMgASgJSAGIAQESEwoLZmlyc3RTZWVuTXMYBCABKAMSEgoKbGFzdFNlZW5NcxgFIAEoAxITCgtpc1JhbmRvbU1hYxgGIAEoCBIWCg5wcm9iZWRGb3JTc2lkcxgHIAMoCRIgChhoYXJkd2FyZU9TU2lnbmF0dXJlU2x1Z3MYCCADKAkSEgoKdmVuZG9yVGFncxgJIAMoCRIlCghpZGVudGl0eRgKIAEoCzIOLmJhc2UuSWRlbnRpdHlIAogBAUIICgZfYWxpYXNCFQoTX3NlY3VyaXR5RXZhbHVhdGlvbkILCglfaWRlbnRpdHlCoAEKCGNvbS5iYXNlQgxEZXZpY2VzUHJvdG9QAVpWZ2l0aHViLmNvbS9oYWNraHVudGVyZGV2L3BpLXNlbnNvcnMvcHVyc3VpdC1hbmQtc29sby9wcm90by1kZWZpbml0aW9ucy9fZ2VuZXJhdGVkL2Jhc2WiAgNCWFiqAgRCYXNlygIEQmFzZeICEEJhc2VcR1BCTWV0YWRhdGHqAgRCYXNlYgZwcm90bzM", [file_base_identity, file_base_auth, file_base_lists, file_base_connection]);

/**
 * @generated from message base.BaseAp
 */
export type BaseAp = Message<"base.BaseAp"> & {
  /**
   * @generated from field: string apId = 1;
   */
  apId: string;

  /**
   * @generated from field: string bssid = 2;
   */
  bssid: string;

  /**
   * @generated from field: string fingerprint = 3;
   */
  fingerprint: string;

  /**
   * @generated from field: string lowestAuthentication = 4;
   */
  lowestAuthentication: string;

  /**
   * @generated from field: repeated string allSupportedAuthentications = 5;
   */
  allSupportedAuthentications: string[];

  /**
   * @generated from field: optional string securityEvaluation = 7;
   */
  securityEvaluation?: string;

  /**
   * @generated from field: optional bool isWifiDirect = 8;
   */
  isWifiDirect?: boolean;

  /**
   * @generated from field: base.ChannelInfo channel = 10;
   */
  channel?: ChannelInfo;

  /**
   * @generated from field: optional string ssid = 11;
   */
  ssid?: string;

  /**
   * @generated from field: optional bool isWPS = 12;
   */
  isWPS?: boolean;

  /**
   * @generated from field: optional bool isNP = 13;
   */
  isNP?: boolean;

  /**
   * @generated from field: optional bool pmfCapable = 14;
   */
  pmfCapable?: boolean;

  /**
   * @generated from field: optional bool pmfRequired = 15;
   */
  pmfRequired?: boolean;

  /**
   * @generated from field: int64 firstSeenMs = 16;
   */
  firstSeenMs: bigint;

  /**
   * @generated from field: int64 lastSeenMs = 17;
   */
  lastSeenMs: bigint;

  /**
   * @generated from field: repeated string vendorTags = 21;
   */
  vendorTags: string[];

  /**
   * @generated from field: optional base.Identity identity = 22;
   */
  identity?: Identity;
};

/**
 * Describes the message base.BaseAp.
 * Use `create(BaseApSchema)` to create a new message.
 */
export const BaseApSchema: GenMessage<BaseAp> = /*@__PURE__*/
  messageDesc(file_base_devices, 0);

/**
 * @generated from message base.BaseStation
 */
export type BaseStation = Message<"base.BaseStation"> & {
  /**
   * @generated from field: string mac = 1;
   */
  mac: string;

  /**
   * @generated from field: optional string alias = 2;
   */
  alias?: string;

  /**
   * @generated from field: optional string securityEvaluation = 3;
   */
  securityEvaluation?: string;

  /**
   * @generated from field: int64 firstSeenMs = 4;
   */
  firstSeenMs: bigint;

  /**
   * @generated from field: int64 lastSeenMs = 5;
   */
  lastSeenMs: bigint;

  /**
   * @generated from field: bool isRandomMac = 6;
   */
  isRandomMac: boolean;

  /**
   * @generated from field: repeated string probedForSsids = 7;
   */
  probedForSsids: string[];

  /**
   * @generated from field: repeated string hardwareOSSignatureSlugs = 8;
   */
  hardwareOSSignatureSlugs: string[];

  /**
   * @generated from field: repeated string vendorTags = 9;
   */
  vendorTags: string[];

  /**
   * @generated from field: optional base.Identity identity = 10;
   */
  identity?: Identity;
};

/**
 * Describes the message base.BaseStation.
 * Use `create(BaseStationSchema)` to create a new message.
 */
export const BaseStationSchema: GenMessage<BaseStation> = /*@__PURE__*/
  messageDesc(file_base_devices, 1);

