// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file base/empty.proto (package base, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file base/empty.proto.
 */
export const file_base_empty: GenFile = /*@__PURE__*/
  fileDesc("ChBiYXNlL2VtcHR5LnByb3RvEgRiYXNlIgcKBUVtcHR5Qp4BCghjb20uYmFzZUIKRW1wdHlQcm90b1ABWlZnaXRodWIuY29tL2hhY2todW50ZXJkZXYvcGktc2Vuc29ycy9wdXJzdWl0LWFuZC1zb2xvL3Byb3RvLWRlZmluaXRpb25zL19nZW5lcmF0ZWQvYmFzZaICA0JYWKoCBEJhc2XKAgRCYXNl4gIQQmFzZVxHUEJNZXRhZGF0YeoCBEJhc2ViBnByb3RvMw");

/**
 * @generated from message base.Empty
 */
export type Empty = Message<"base.Empty"> & {
};

/**
 * Describes the message base.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema: GenMessage<Empty> = /*@__PURE__*/
  messageDesc(file_base_empty, 0);

