// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file base/identity.proto (package base, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file base/identity.proto.
 */
export const file_base_identity: GenFile = /*@__PURE__*/
  fileDesc("ChNiYXNlL2lkZW50aXR5LnByb3RvEgRiYXNlIlgKCElkZW50aXR5EgwKBGljb24YASABKAkSFAoMZmFsbGJhY2tJY29uGAIgASgJEgwKBG5hbWUYAyABKAkSGgoSc2VjdXJpdHlFdmFsdWF0aW9uGAQgASgJQqEBCghjb20uYmFzZUINSWRlbnRpdHlQcm90b1ABWlZnaXRodWIuY29tL2hhY2todW50ZXJkZXYvcGktc2Vuc29ycy9wdXJzdWl0LWFuZC1zb2xvL3Byb3RvLWRlZmluaXRpb25zL19nZW5lcmF0ZWQvYmFzZaICA0JYWKoCBEJhc2XKAgRCYXNl4gIQQmFzZVxHUEJNZXRhZGF0YeoCBEJhc2ViBnByb3RvMw");

/**
 * @generated from message base.Identity
 */
export type Identity = Message<"base.Identity"> & {
  /**
   * @generated from field: string icon = 1;
   */
  icon: string;

  /**
   * @generated from field: string fallbackIcon = 2;
   */
  fallbackIcon: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string securityEvaluation = 4;
   */
  securityEvaluation: string;
};

/**
 * Describes the message base.Identity.
 * Use `create(IdentitySchema)` to create a new message.
 */
export const IdentitySchema: GenMessage<Identity> = /*@__PURE__*/
  messageDesc(file_base_identity, 0);

