// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file base/isr.proto (package base, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file base/isr.proto.
 */
export const file_base_isr: GenFile = /*@__PURE__*/
  fileDesc("Cg5iYXNlL2lzci5wcm90bxIEYmFzZSI/Cg1Jc3JEZXZpY2VJbmZvEi4KD2lzck1hdGNoRGV0YWlscxgBIAMoCzIVLmJhc2UuSXNyTWF0Y2hEZXRhaWxzIsUBCg9Jc3JNYXRjaERldGFpbHMSDQoFY29sb3IYASABKAkSDwoHZ3JvdXBJZBgCIAEoCRIRCglncm91cE5hbWUYAyABKAkSEAoIdGFyZ2V0SWQYBCABKAkSEgoKdGFyZ2V0TmFtZRgFIAEoCRIYChBtYXRjaFN0cmVuZ3RoU3RyGAYgASgJEhUKDW1hdGNoU3RyZW5ndGgYByABKA0SKAoMbWF0Y2hSZWFzb25zGAggAygLMhIuYmFzZS5NYXRjaFJlYXNvbnMiMQoMTWF0Y2hSZWFzb25zEhMKC1N1YkxldmVsTnVtGAEgASgNEgwKBHRleHQYAiABKAlCnAEKCGNvbS5iYXNlQghJc3JQcm90b1ABWlZnaXRodWIuY29tL2hhY2todW50ZXJkZXYvcGktc2Vuc29ycy9wdXJzdWl0LWFuZC1zb2xvL3Byb3RvLWRlZmluaXRpb25zL19nZW5lcmF0ZWQvYmFzZaICA0JYWKoCBEJhc2XKAgRCYXNl4gIQQmFzZVxHUEJNZXRhZGF0YeoCBEJhc2ViBnByb3RvMw");

/**
 * @generated from message base.IsrDeviceInfo
 */
export type IsrDeviceInfo = Message<"base.IsrDeviceInfo"> & {
  /**
   * @generated from field: repeated base.IsrMatchDetails isrMatchDetails = 1;
   */
  isrMatchDetails: IsrMatchDetails[];
};

/**
 * Describes the message base.IsrDeviceInfo.
 * Use `create(IsrDeviceInfoSchema)` to create a new message.
 */
export const IsrDeviceInfoSchema: GenMessage<IsrDeviceInfo> = /*@__PURE__*/
  messageDesc(file_base_isr, 0);

/**
 * @generated from message base.IsrMatchDetails
 */
export type IsrMatchDetails = Message<"base.IsrMatchDetails"> & {
  /**
   * @generated from field: string color = 1;
   */
  color: string;

  /**
   * @generated from field: string groupId = 2;
   */
  groupId: string;

  /**
   * @generated from field: string groupName = 3;
   */
  groupName: string;

  /**
   * @generated from field: string targetId = 4;
   */
  targetId: string;

  /**
   * @generated from field: string targetName = 5;
   */
  targetName: string;

  /**
   * @generated from field: string matchStrengthStr = 6;
   */
  matchStrengthStr: string;

  /**
   * @generated from field: uint32 matchStrength = 7;
   */
  matchStrength: number;

  /**
   * @generated from field: repeated base.MatchReasons matchReasons = 8;
   */
  matchReasons: MatchReasons[];
};

/**
 * Describes the message base.IsrMatchDetails.
 * Use `create(IsrMatchDetailsSchema)` to create a new message.
 */
export const IsrMatchDetailsSchema: GenMessage<IsrMatchDetails> = /*@__PURE__*/
  messageDesc(file_base_isr, 1);

/**
 * @generated from message base.MatchReasons
 */
export type MatchReasons = Message<"base.MatchReasons"> & {
  /**
   * @generated from field: uint32 SubLevelNum = 1;
   */
  SubLevelNum: number;

  /**
   * @generated from field: string text = 2;
   */
  text: string;
};

/**
 * Describes the message base.MatchReasons.
 * Use `create(MatchReasonsSchema)` to create a new message.
 */
export const MatchReasonsSchema: GenMessage<MatchReasons> = /*@__PURE__*/
  messageDesc(file_base_isr, 2);

