// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file base/requests.proto (package base, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file base/requests.proto.
 */
export const file_base_requests: GenFile = /*@__PURE__*/
  fileDesc("ChNiYXNlL3JlcXVlc3RzLnByb3RvEgRiYXNlIjcKGlJlcXVlc3RXaXRoTGFzdFByb2Nlc3NlZEF0EhkKEWxhc3RQcm9jZXNzZWRBdE1zGAEgASgEQqEBCghjb20uYmFzZUINUmVxdWVzdHNQcm90b1ABWlZnaXRodWIuY29tL2hhY2todW50ZXJkZXYvcGktc2Vuc29ycy9wdXJzdWl0LWFuZC1zb2xvL3Byb3RvLWRlZmluaXRpb25zL19nZW5lcmF0ZWQvYmFzZaICA0JYWKoCBEJhc2XKAgRCYXNl4gIQQmFzZVxHUEJNZXRhZGF0YeoCBEJhc2ViBnByb3RvMw");

/**
 * @generated from message base.RequestWithLastProcessedAt
 */
export type RequestWithLastProcessedAt = Message<"base.RequestWithLastProcessedAt"> & {
  /**
   * @generated from field: uint64 lastProcessedAtMs = 1;
   */
  lastProcessedAtMs: bigint;
};

/**
 * Describes the message base.RequestWithLastProcessedAt.
 * Use `create(RequestWithLastProcessedAtSchema)` to create a new message.
 */
export const RequestWithLastProcessedAtSchema: GenMessage<RequestWithLastProcessedAt> = /*@__PURE__*/
  messageDesc(file_base_requests, 0);

