// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file services/health/health.proto (package health, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "../../base/empty_pb";
import { file_base_empty } from "../../base/empty_pb";
import { file_base_requests } from "../../base/requests_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file services/health/health.proto.
 */
export const file_services_health_health: GenFile = /*@__PURE__*/
  fileDesc("ChxzZXJ2aWNlcy9oZWFsdGgvaGVhbHRoLnByb3RvEgZoZWFsdGgiIgoQSGVhbHRoQ2hlY2tSZXBseRIOCgZzdGF0dXMYASABKAgyRwoNSGVhbHRoU2VydmljZRI2CgtIZWFsdGhDaGVjaxILLmJhc2UuRW1wdHkaGC5oZWFsdGguSGVhbHRoQ2hlY2tSZXBseSIAQrQBCgpjb20uaGVhbHRoQgtIZWFsdGhQcm90b1ABWmFnaXRodWIuY29tL2hhY2todW50ZXJkZXYvcGktc2Vuc29ycy9wdXJzdWl0LWFuZC1zb2xvL3Byb3RvLWRlZmluaXRpb25zL19nZW5lcmF0ZWQvc2VydmljZXMvaGVhbHRoogIDSFhYqgIGSGVhbHRoygIGSGVhbHRo4gISSGVhbHRoXEdQQk1ldGFkYXRh6gIGSGVhbHRoYgZwcm90bzM", [file_base_empty, file_base_requests]);

/**
 * @generated from message health.HealthCheckReply
 */
export type HealthCheckReply = Message<"health.HealthCheckReply"> & {
  /**
   * @generated from field: bool status = 1;
   */
  status: boolean;
};

/**
 * Describes the message health.HealthCheckReply.
 * Use `create(HealthCheckReplySchema)` to create a new message.
 */
export const HealthCheckReplySchema: GenMessage<HealthCheckReply> = /*@__PURE__*/
  messageDesc(file_services_health_health, 0);

/**
 * @generated from service health.HealthService
 */
export const HealthService: GenService<{
  /**
   * @generated from rpc health.HealthService.HealthCheck
   */
  healthCheck: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof HealthCheckReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_services_health_health, 0);

