// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file services/license/license.proto (package license, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "../../base/empty_pb";
import { file_base_empty } from "../../base/empty_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file services/license/license.proto.
 */
export const file_services_license_license: GenFile = /*@__PURE__*/
  fileDesc("Ch5zZXJ2aWNlcy9saWNlbnNlL2xpY2Vuc2UucHJvdG8SB2xpY2Vuc2UiZwoWR2V0TGljZW5zZURldGFpbHNSZXBseRIfChdyZW1haW5pbmdMaWNlbnNlTWludXRlcxgBIAEoDRIbChNsaWNlbnNlRXhwaXJ5RGF0ZU1zGAIgASgDEg8KB2lzVmFsaWQYAyABKAgyVQoOTGljZW5zZVNlcnZpY2USQwoRR2V0TGljZW5zZURldGFpbHMSCy5iYXNlLkVtcHR5Gh8ubGljZW5zZS5HZXRMaWNlbnNlRGV0YWlsc1JlcGx5IgBCuwEKC2NvbS5saWNlbnNlQgxMaWNlbnNlUHJvdG9QAVpiZ2l0aHViLmNvbS9oYWNraHVudGVyZGV2L3BpLXNlbnNvcnMvcHVyc3VpdC1hbmQtc29sby9wcm90by1kZWZpbml0aW9ucy9fZ2VuZXJhdGVkL3NlcnZpY2VzL2xpY2Vuc2WiAgNMWFiqAgdMaWNlbnNlygIHTGljZW5zZeICE0xpY2Vuc2VcR1BCTWV0YWRhdGHqAgdMaWNlbnNlYgZwcm90bzM", [file_base_empty]);

/**
 * @generated from message license.GetLicenseDetailsReply
 */
export type GetLicenseDetailsReply = Message<"license.GetLicenseDetailsReply"> & {
  /**
   * @generated from field: uint32 remainingLicenseMinutes = 1;
   */
  remainingLicenseMinutes: number;

  /**
   * @generated from field: int64 licenseExpiryDateMs = 2;
   */
  licenseExpiryDateMs: bigint;

  /**
   * @generated from field: bool isValid = 3;
   */
  isValid: boolean;
};

/**
 * Describes the message license.GetLicenseDetailsReply.
 * Use `create(GetLicenseDetailsReplySchema)` to create a new message.
 */
export const GetLicenseDetailsReplySchema: GenMessage<GetLicenseDetailsReply> = /*@__PURE__*/
  messageDesc(file_services_license_license, 0);

/**
 * @generated from service license.LicenseService
 */
export const LicenseService: GenService<{
  /**
   * @generated from rpc license.LicenseService.GetLicenseDetails
   */
  getLicenseDetails: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof GetLicenseDetailsReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_services_license_license, 0);

