// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file services/eula/eula.proto (package eula, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "../../base/empty_pb";
import { file_base_empty } from "../../base/empty_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file services/eula/eula.proto.
 */
export const file_services_eula_eula: GenFile = /*@__PURE__*/
  fileDesc("ChhzZXJ2aWNlcy9ldWxhL2V1bGEucHJvdG8SBGV1bGEiHAoMR2V0RXVsYVJlcGx5EgwKBGV1bGEYASABKAkyOwoLRXVsYVNlcnZpY2USLAoHR2V0RXVsYRILLmJhc2UuRW1wdHkaEi5ldWxhLkdldEV1bGFSZXBseSIAQqYBCghjb20uZXVsYUIJRXVsYVByb3RvUAFaX2dpdGh1Yi5jb20vaGFja2h1bnRlcmRldi9waS1zZW5zb3JzL3B1cnN1aXQtYW5kLXNvbG8vcHJvdG8tZGVmaW5pdGlvbnMvX2dlbmVyYXRlZC9zZXJ2aWNlcy9ldWxhogIDRVhYqgIERXVsYcoCBEV1bGHiAhBFdWxhXEdQQk1ldGFkYXRh6gIERXVsYWIGcHJvdG8z", [file_base_empty]);

/**
 * @generated from message eula.GetEulaReply
 */
export type GetEulaReply = Message<"eula.GetEulaReply"> & {
  /**
   * @generated from field: string eula = 1;
   */
  eula: string;
};

/**
 * Describes the message eula.GetEulaReply.
 * Use `create(GetEulaReplySchema)` to create a new message.
 */
export const GetEulaReplySchema: GenMessage<GetEulaReply> = /*@__PURE__*/
  messageDesc(file_services_eula_eula, 0);

/**
 * @generated from service eula.EulaService
 */
export const EulaService: GenService<{
  /**
   * @generated from rpc eula.EulaService.GetEula
   */
  getEula: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof GetEulaReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_services_eula_eula, 0);

