// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file services/features/features.proto (package features, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "../../base/empty_pb";
import { file_base_empty } from "../../base/empty_pb";
import { file_base_requests } from "../../base/requests_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file services/features/features.proto.
 */
export const file_services_features_features: GenFile = /*@__PURE__*/
  fileDesc("CiBzZXJ2aWNlcy9mZWF0dXJlcy9mZWF0dXJlcy5wcm90bxIIZmVhdHVyZXMiswEKEEdldEZlYXR1cmVzUmVwbHkSFwoPaXNPZmZsaW5lRGV2aWNlGAEgASgIEhMKC2lzSVNSRGV2aWNlGAIgASgIEhMKC2lzRGV2RGV2aWNlGAMgASgIEhwKFGRldmljZVRhZ2dpbmdFbmFibGVkGAQgASgIEhkKEWRpc2FibGVBbGxMb2dnaW5nGAUgASgIEiMKG2FsbG93SVNSQ29tbWVyY2lhbFN3aXRjaGluZxgGIAEoCDJKCg5GZWF0dXJlU2VydmljZRI4CgtHZXRGZWF0dXJlcxILLmJhc2UuRW1wdHkaGi5mZWF0dXJlcy5HZXRGZWF0dXJlc1JlcGx5IgBCwgEKDGNvbS5mZWF0dXJlc0INRmVhdHVyZXNQcm90b1ABWmNnaXRodWIuY29tL2hhY2todW50ZXJkZXYvcGktc2Vuc29ycy9wdXJzdWl0LWFuZC1zb2xvL3Byb3RvLWRlZmluaXRpb25zL19nZW5lcmF0ZWQvc2VydmljZXMvZmVhdHVyZXOiAgNGWFiqAghGZWF0dXJlc8oCCEZlYXR1cmVz4gIURmVhdHVyZXNcR1BCTWV0YWRhdGHqAghGZWF0dXJlc2IGcHJvdG8z", [file_base_empty, file_base_requests]);

/**
 * @generated from message features.GetFeaturesReply
 */
export type GetFeaturesReply = Message<"features.GetFeaturesReply"> & {
  /**
   * @generated from field: bool isOfflineDevice = 1;
   */
  isOfflineDevice: boolean;

  /**
   * @generated from field: bool isISRDevice = 2;
   */
  isISRDevice: boolean;

  /**
   * @generated from field: bool isDevDevice = 3;
   */
  isDevDevice: boolean;

  /**
   * @generated from field: bool deviceTaggingEnabled = 4;
   */
  deviceTaggingEnabled: boolean;

  /**
   * @generated from field: bool disableAllLogging = 5;
   */
  disableAllLogging: boolean;

  /**
   * @generated from field: bool allowISRCommercialSwitching = 6;
   */
  allowISRCommercialSwitching: boolean;
};

/**
 * Describes the message features.GetFeaturesReply.
 * Use `create(GetFeaturesReplySchema)` to create a new message.
 */
export const GetFeaturesReplySchema: GenMessage<GetFeaturesReply> = /*@__PURE__*/
  messageDesc(file_services_features_features, 0);

/**
 * @generated from service features.FeatureService
 */
export const FeatureService: GenService<{
  /**
   * @generated from rpc features.FeatureService.GetFeatures
   */
  getFeatures: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof GetFeaturesReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_services_features_features, 0);

