// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file services/about/about.proto (package about, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "../../base/empty_pb";
import { file_base_empty } from "../../base/empty_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file services/about/about.proto.
 */
export const file_services_about_about: GenFile = /*@__PURE__*/
  fileDesc("ChpzZXJ2aWNlcy9hYm91dC9hYm91dC5wcm90bxIFYWJvdXQiSAoUR2V0QWJvdXREZXRhaWxzUmVwbHkSGQoRaXNVcGRhdGVBdmFpbGFibGUYASABKAgSFQoNdXBkYXRlVmVyc2lvbhgCIAEoCTJ5Cg1VcGRhdGVTZXJ2aWNlEj0KD0dldEFib3V0RGV0YWlscxILLmJhc2UuRW1wdHkaGy5hYm91dC5HZXRBYm91dERldGFpbHNSZXBseSIAEikKC1N0YXJ0VXBkYXRlEgsuYmFzZS5FbXB0eRoLLmJhc2UuRW1wdHkiAEKtAQoJY29tLmFib3V0QgpBYm91dFByb3RvUAFaYGdpdGh1Yi5jb20vaGFja2h1bnRlcmRldi9waS1zZW5zb3JzL3B1cnN1aXQtYW5kLXNvbG8vcHJvdG8tZGVmaW5pdGlvbnMvX2dlbmVyYXRlZC9zZXJ2aWNlcy9hYm91dKICA0FYWKoCBUFib3V0ygIFQWJvdXTiAhFBYm91dFxHUEJNZXRhZGF0YeoCBUFib3V0YgZwcm90bzM", [file_base_empty]);

/**
 * @generated from message about.GetAboutDetailsReply
 */
export type GetAboutDetailsReply = Message<"about.GetAboutDetailsReply"> & {
  /**
   * @generated from field: bool isUpdateAvailable = 1;
   */
  isUpdateAvailable: boolean;

  /**
   * @generated from field: string updateVersion = 2;
   */
  updateVersion: string;
};

/**
 * Describes the message about.GetAboutDetailsReply.
 * Use `create(GetAboutDetailsReplySchema)` to create a new message.
 */
export const GetAboutDetailsReplySchema: GenMessage<GetAboutDetailsReply> = /*@__PURE__*/
  messageDesc(file_services_about_about, 0);

/**
 * @generated from service about.UpdateService
 */
export const UpdateService: GenService<{
  /**
   * @generated from rpc about.UpdateService.GetAboutDetails
   */
  getAboutDetails: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof GetAboutDetailsReplySchema;
  },
  /**
   * @generated from rpc about.UpdateService.StartUpdate
   */
  startUpdate: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_services_about_about, 0);

