// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file services/sysinfo/sysinfo.proto (package isr, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "../../base/empty_pb";
import { file_base_empty } from "../../base/empty_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file services/sysinfo/sysinfo.proto.
 */
export const file_services_sysinfo_sysinfo: GenFile = /*@__PURE__*/
  fileDesc("Ch5zZXJ2aWNlcy9zeXNpbmZvL3N5c2luZm8ucHJvdG8SA2lzciKtAQoPR2V0U3lzSW5mb1JlcGx5EgwKBG5hbWUYASABKAkSEAoIY2FyZFNpemUYAiABKAkSEAoIY2xpZW50SWQYAyABKAkSJAoLaXBBZGRyZXNzZXMYBCADKAsyDy5pc3IuU3lzSXBFbnRyeRIsCgtkaWFnbm9zdGljcxgFIAEoCzIXLmlzci5TeXNJbmZvRGlhZ25vc3RpY3MSFAoMc2VyaWFsTnVtYmVyGAYgASgJIigKClN5c0lwRW50cnkSCgoCaXAYASABKAkSDgoGZGV2aWNlGAIgASgJIp8BChJTeXNJbmZvRGlhZ25vc3RpY3MSDwoHY3B1VGVtcBgBIAEoBRIXCg9jcHVVc2FnZVBlcmNlbnQYAiABKAUSDwoHZ3B1VGVtcBgDIAEoBRIXCg9yYW1Vc2FnZVBlcmNlbnQYBCABKAUSGgoSc2RDYXJkVXNhZ2VQZXJjZW50GAUgASgFEhkKEWZsYXNoVXNhZ2VQZXJjZW50GAYgASgFMmkKDlN5c0luZm9TZXJ2aWNlEjEKCkdldFN5c0luZm8SCy5iYXNlLkVtcHR5GhQuaXNyLkdldFN5c0luZm9SZXBseSIAEiQKBlJlYm9vdBILLmJhc2UuRW1wdHkaCy5iYXNlLkVtcHR5IgBCpwEKB2NvbS5pc3JCDFN5c2luZm9Qcm90b1ABWmJnaXRodWIuY29tL2hhY2todW50ZXJkZXYvcGktc2Vuc29ycy9wdXJzdWl0LWFuZC1zb2xvL3Byb3RvLWRlZmluaXRpb25zL19nZW5lcmF0ZWQvc2VydmljZXMvc3lzaW5mb6ICA0lYWKoCA0lzcsoCA0lzcuICD0lzclxHUEJNZXRhZGF0YeoCA0lzcmIGcHJvdG8z", [file_base_empty]);

/**
 * @generated from message isr.GetSysInfoReply
 */
export type GetSysInfoReply = Message<"isr.GetSysInfoReply"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string cardSize = 2;
   */
  cardSize: string;

  /**
   * @generated from field: string clientId = 3;
   */
  clientId: string;

  /**
   * @generated from field: repeated isr.SysIpEntry ipAddresses = 4;
   */
  ipAddresses: SysIpEntry[];

  /**
   * @generated from field: isr.SysInfoDiagnostics diagnostics = 5;
   */
  diagnostics?: SysInfoDiagnostics;

  /**
   * @generated from field: string serialNumber = 6;
   */
  serialNumber: string;
};

/**
 * Describes the message isr.GetSysInfoReply.
 * Use `create(GetSysInfoReplySchema)` to create a new message.
 */
export const GetSysInfoReplySchema: GenMessage<GetSysInfoReply> = /*@__PURE__*/
  messageDesc(file_services_sysinfo_sysinfo, 0);

/**
 * @generated from message isr.SysIpEntry
 */
export type SysIpEntry = Message<"isr.SysIpEntry"> & {
  /**
   * @generated from field: string ip = 1;
   */
  ip: string;

  /**
   * @generated from field: string device = 2;
   */
  device: string;
};

/**
 * Describes the message isr.SysIpEntry.
 * Use `create(SysIpEntrySchema)` to create a new message.
 */
export const SysIpEntrySchema: GenMessage<SysIpEntry> = /*@__PURE__*/
  messageDesc(file_services_sysinfo_sysinfo, 1);

/**
 * @generated from message isr.SysInfoDiagnostics
 */
export type SysInfoDiagnostics = Message<"isr.SysInfoDiagnostics"> & {
  /**
   * @generated from field: int32 cpuTemp = 1;
   */
  cpuTemp: number;

  /**
   * @generated from field: int32 cpuUsagePercent = 2;
   */
  cpuUsagePercent: number;

  /**
   * @generated from field: int32 gpuTemp = 3;
   */
  gpuTemp: number;

  /**
   * @generated from field: int32 ramUsagePercent = 4;
   */
  ramUsagePercent: number;

  /**
   * @generated from field: int32 sdCardUsagePercent = 5;
   */
  sdCardUsagePercent: number;

  /**
   * @generated from field: int32 flashUsagePercent = 6;
   */
  flashUsagePercent: number;
};

/**
 * Describes the message isr.SysInfoDiagnostics.
 * Use `create(SysInfoDiagnosticsSchema)` to create a new message.
 */
export const SysInfoDiagnosticsSchema: GenMessage<SysInfoDiagnostics> = /*@__PURE__*/
  messageDesc(file_services_sysinfo_sysinfo, 2);

/**
 * @generated from service isr.SysInfoService
 */
export const SysInfoService: GenService<{
  /**
   * @generated from rpc isr.SysInfoService.GetSysInfo
   */
  getSysInfo: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof GetSysInfoReplySchema;
  },
  /**
   * @generated from rpc isr.SysInfoService.Reboot
   */
  reboot: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_services_sysinfo_sysinfo, 0);

