// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file services/deauth/deauth.proto (package deauth, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "../../base/empty_pb";
import { file_base_empty } from "../../base/empty_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file services/deauth/deauth.proto.
 */
export const file_services_deauth_deauth: GenFile = /*@__PURE__*/
  fileDesc("ChxzZXJ2aWNlcy9kZWF1dGgvZGVhdXRoLnByb3RvEgZkZWF1dGgicwoNRGVhdXRoVGFyZ2V0cxIuCgtsaXZlVGFyZ2V0cxgBIAEoCzIZLmRlYXV0aC5EZWF1dGhUYXJnZXRzTGl2ZRIyCg1tYW51YWxUYXJnZXRzGAIgASgLMhsuZGVhdXRoLkRlYXV0aFRhcmdldHNNYW51YWwiUAoRRGVhdXRoVGFyZ2V0c0xpdmUSFAoMbmV0d29ya1NzaWRzGAEgAygJEhMKC3N0YXRpb25NYWNzGAIgAygJEhAKCGFwQnNzaWRzGAMgAygJInUKE0RlYXV0aFRhcmdldHNNYW51YWwSMwoObmV0d29ya1RhcmdldHMYASADKAsyGy5kZWF1dGguTWFudWFsTmV0d29ya1RhcmdldBIpCglhcFRhcmdldHMYAiADKAsyFi5kZWF1dGguTWFudWFsQXBUYXJnZXQiNwoTTWFudWFsTmV0d29ya1RhcmdldBITCgtuZXR3b3JrU3NpZBgBIAEoCRILCgNtYWMYAiABKAkiLAoOTWFudWFsQXBUYXJnZXQSDQoFYnNzaWQYASABKAkSCwoDbWFjGAIgASgJIkwKDURlYXV0aERldGFpbHMSEwoLaXNEZWF1dGhpbmcYASABKAgSJgoHdGFyZ2V0cxgCIAEoCzIVLmRlYXV0aC5EZWF1dGhUYXJnZXRzMocCCg1EZWF1dGhTZXJ2aWNlEj0KC1N0YXJ0RGVhdXRoEhUuZGVhdXRoLkRlYXV0aFRhcmdldHMaFS5kZWF1dGguRGVhdXRoRGV0YWlscyIAEjIKClN0b3BEZWF1dGgSCy5iYXNlLkVtcHR5GhUuZGVhdXRoLkRlYXV0aERldGFpbHMiABJFChNVcGRhdGVEZWF1dGhUYXJnZXRzEhUuZGVhdXRoLkRlYXV0aFRhcmdldHMaFS5kZWF1dGguRGVhdXRoRGV0YWlscyIAEjwKFEdldEN1cnJlbnREZWF1dGhJbmZvEgsuYmFzZS5FbXB0eRoVLmRlYXV0aC5EZWF1dGhEZXRhaWxzIgBCtAEKCmNvbS5kZWF1dGhCC0RlYXV0aFByb3RvUAFaYWdpdGh1Yi5jb20vaGFja2h1bnRlcmRldi9waS1zZW5zb3JzL3B1cnN1aXQtYW5kLXNvbG8vcHJvdG8tZGVmaW5pdGlvbnMvX2dlbmVyYXRlZC9zZXJ2aWNlcy9kZWF1dGiiAgNEWFiqAgZEZWF1dGjKAgZEZWF1dGjiAhJEZWF1dGhcR1BCTWV0YWRhdGHqAgZEZWF1dGhiBnByb3RvMw", [file_base_empty]);

/**
 * @generated from message deauth.DeauthTargets
 */
export type DeauthTargets = Message<"deauth.DeauthTargets"> & {
  /**
   * @generated from field: deauth.DeauthTargetsLive liveTargets = 1;
   */
  liveTargets?: DeauthTargetsLive;

  /**
   * @generated from field: deauth.DeauthTargetsManual manualTargets = 2;
   */
  manualTargets?: DeauthTargetsManual;
};

/**
 * Describes the message deauth.DeauthTargets.
 * Use `create(DeauthTargetsSchema)` to create a new message.
 */
export const DeauthTargetsSchema: GenMessage<DeauthTargets> = /*@__PURE__*/
  messageDesc(file_services_deauth_deauth, 0);

/**
 * @generated from message deauth.DeauthTargetsLive
 */
export type DeauthTargetsLive = Message<"deauth.DeauthTargetsLive"> & {
  /**
   * @generated from field: repeated string networkSsids = 1;
   */
  networkSsids: string[];

  /**
   * @generated from field: repeated string stationMacs = 2;
   */
  stationMacs: string[];

  /**
   * @generated from field: repeated string apBssids = 3;
   */
  apBssids: string[];
};

/**
 * Describes the message deauth.DeauthTargetsLive.
 * Use `create(DeauthTargetsLiveSchema)` to create a new message.
 */
export const DeauthTargetsLiveSchema: GenMessage<DeauthTargetsLive> = /*@__PURE__*/
  messageDesc(file_services_deauth_deauth, 1);

/**
 * @generated from message deauth.DeauthTargetsManual
 */
export type DeauthTargetsManual = Message<"deauth.DeauthTargetsManual"> & {
  /**
   * @generated from field: repeated deauth.ManualNetworkTarget networkTargets = 1;
   */
  networkTargets: ManualNetworkTarget[];

  /**
   * @generated from field: repeated deauth.ManualApTarget apTargets = 2;
   */
  apTargets: ManualApTarget[];
};

/**
 * Describes the message deauth.DeauthTargetsManual.
 * Use `create(DeauthTargetsManualSchema)` to create a new message.
 */
export const DeauthTargetsManualSchema: GenMessage<DeauthTargetsManual> = /*@__PURE__*/
  messageDesc(file_services_deauth_deauth, 2);

/**
 * @generated from message deauth.ManualNetworkTarget
 */
export type ManualNetworkTarget = Message<"deauth.ManualNetworkTarget"> & {
  /**
   * @generated from field: string networkSsid = 1;
   */
  networkSsid: string;

  /**
   * @generated from field: string mac = 2;
   */
  mac: string;
};

/**
 * Describes the message deauth.ManualNetworkTarget.
 * Use `create(ManualNetworkTargetSchema)` to create a new message.
 */
export const ManualNetworkTargetSchema: GenMessage<ManualNetworkTarget> = /*@__PURE__*/
  messageDesc(file_services_deauth_deauth, 3);

/**
 * @generated from message deauth.ManualApTarget
 */
export type ManualApTarget = Message<"deauth.ManualApTarget"> & {
  /**
   * @generated from field: string bssid = 1;
   */
  bssid: string;

  /**
   * @generated from field: string mac = 2;
   */
  mac: string;
};

/**
 * Describes the message deauth.ManualApTarget.
 * Use `create(ManualApTargetSchema)` to create a new message.
 */
export const ManualApTargetSchema: GenMessage<ManualApTarget> = /*@__PURE__*/
  messageDesc(file_services_deauth_deauth, 4);

/**
 * @generated from message deauth.DeauthDetails
 */
export type DeauthDetails = Message<"deauth.DeauthDetails"> & {
  /**
   * @generated from field: bool isDeauthing = 1;
   */
  isDeauthing: boolean;

  /**
   * @generated from field: deauth.DeauthTargets targets = 2;
   */
  targets?: DeauthTargets;
};

/**
 * Describes the message deauth.DeauthDetails.
 * Use `create(DeauthDetailsSchema)` to create a new message.
 */
export const DeauthDetailsSchema: GenMessage<DeauthDetails> = /*@__PURE__*/
  messageDesc(file_services_deauth_deauth, 5);

/**
 * @generated from service deauth.DeauthService
 */
export const DeauthService: GenService<{
  /**
   * @generated from rpc deauth.DeauthService.StartDeauth
   */
  startDeauth: {
    methodKind: "unary";
    input: typeof DeauthTargetsSchema;
    output: typeof DeauthDetailsSchema;
  },
  /**
   * @generated from rpc deauth.DeauthService.StopDeauth
   */
  stopDeauth: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof DeauthDetailsSchema;
  },
  /**
   * @generated from rpc deauth.DeauthService.UpdateDeauthTargets
   */
  updateDeauthTargets: {
    methodKind: "unary";
    input: typeof DeauthTargetsSchema;
    output: typeof DeauthDetailsSchema;
  },
  /**
   * @generated from rpc deauth.DeauthService.GetCurrentDeauthInfo
   */
  getCurrentDeauthInfo: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof DeauthDetailsSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_services_deauth_deauth, 0);

