// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file services/oui/oui.proto (package oui, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file services/oui/oui.proto.
 */
export const file_services_oui_oui: GenFile = /*@__PURE__*/
  fileDesc("ChZzZXJ2aWNlcy9vdWkvb3VpLnByb3RvEgNvdWkiIgoTR2V0T3VpRm9yTWFjUmVxdWVzdBILCgNtYWMYASABKAkiOAoRR2V0T3VpRm9yTWFjUmVwbHkSIwoKb3VpRGV0YWlscxgBIAEoCzIPLm91aS5PdWlEZXRhaWxzIoIBCgpPdWlEZXRhaWxzEg4KBmhhc091aRgBIAEoCBIVCghzaG9ydE91aRgCIAEoCUgAiAEBEhQKB2xvbmdPdWkYAyABKAlIAYgBARITCgZvdWlNYWMYBCABKAlIAogBAUILCglfc2hvcnRPdWlCCgoIX2xvbmdPdWlCCQoHX291aU1hYzJQCgpPdWlTZXJ2aWNlEkIKDEdldE91aUZvck1hYxIYLm91aS5HZXRPdWlGb3JNYWNSZXF1ZXN0GhYub3VpLkdldE91aUZvck1hY1JlcGx5IgBCnwEKB2NvbS5vdWlCCE91aVByb3RvUAFaXmdpdGh1Yi5jb20vaGFja2h1bnRlcmRldi9waS1zZW5zb3JzL3B1cnN1aXQtYW5kLXNvbG8vcHJvdG8tZGVmaW5pdGlvbnMvX2dlbmVyYXRlZC9zZXJ2aWNlcy9vdWmiAgNPWFiqAgNPdWnKAgNPdWniAg9PdWlcR1BCTWV0YWRhdGHqAgNPdWliBnByb3RvMw");

/**
 * @generated from message oui.GetOuiForMacRequest
 */
export type GetOuiForMacRequest = Message<"oui.GetOuiForMacRequest"> & {
  /**
   * @generated from field: string mac = 1;
   */
  mac: string;
};

/**
 * Describes the message oui.GetOuiForMacRequest.
 * Use `create(GetOuiForMacRequestSchema)` to create a new message.
 */
export const GetOuiForMacRequestSchema: GenMessage<GetOuiForMacRequest> = /*@__PURE__*/
  messageDesc(file_services_oui_oui, 0);

/**
 * @generated from message oui.GetOuiForMacReply
 */
export type GetOuiForMacReply = Message<"oui.GetOuiForMacReply"> & {
  /**
   * @generated from field: oui.OuiDetails ouiDetails = 1;
   */
  ouiDetails?: OuiDetails;
};

/**
 * Describes the message oui.GetOuiForMacReply.
 * Use `create(GetOuiForMacReplySchema)` to create a new message.
 */
export const GetOuiForMacReplySchema: GenMessage<GetOuiForMacReply> = /*@__PURE__*/
  messageDesc(file_services_oui_oui, 1);

/**
 * @generated from message oui.OuiDetails
 */
export type OuiDetails = Message<"oui.OuiDetails"> & {
  /**
   * @generated from field: bool hasOui = 1;
   */
  hasOui: boolean;

  /**
   * @generated from field: optional string shortOui = 2;
   */
  shortOui?: string;

  /**
   * @generated from field: optional string longOui = 3;
   */
  longOui?: string;

  /**
   * @generated from field: optional string ouiMac = 4;
   */
  ouiMac?: string;
};

/**
 * Describes the message oui.OuiDetails.
 * Use `create(OuiDetailsSchema)` to create a new message.
 */
export const OuiDetailsSchema: GenMessage<OuiDetails> = /*@__PURE__*/
  messageDesc(file_services_oui_oui, 2);

/**
 * @generated from service oui.OuiService
 */
export const OuiService: GenService<{
  /**
   * @generated from rpc oui.OuiService.GetOuiForMac
   */
  getOuiForMac: {
    methodKind: "unary";
    input: typeof GetOuiForMacRequestSchema;
    output: typeof GetOuiForMacReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_services_oui_oui, 0);

