// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file services/list/list.proto (package list, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { UserList } from "../../base/lists_pb";
import { file_base_lists } from "../../base/lists_pb";
import type { EmptySchema } from "../../base/empty_pb";
import { file_base_empty } from "../../base/empty_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file services/list/list.proto.
 */
export const file_services_list_list: GenFile = /*@__PURE__*/
  fileDesc("ChhzZXJ2aWNlcy9saXN0L2xpc3QucHJvdG8SBGxpc3QiQwoSQXNzaWduTGlzdHNSZXF1ZXN0Ei0KD2xpc3RBc3NpZ25tZW50cxgBIAMoCzIULmxpc3QuTGlzdEFzc2lnbm1lbnQiOwoOTGlzdEFzc2lnbm1lbnQSCwoDbWFjGAEgASgJEhwKBGxpc3QYAiABKA4yDi5iYXNlLlVzZXJMaXN0MkQKC0xpc3RTZXJ2aWNlEjUKCkFzc2lnbkxpc3QSGC5saXN0LkFzc2lnbkxpc3RzUmVxdWVzdBoLLmJhc2UuRW1wdHkiAEKoAQoIY29tLmxpc3RCCUxpc3RQcm90b1ABWl9naXRodWIuY29tL2hhY2todW50ZXJkZXYvcGktc2Vuc29ycy9wdXJzdWl0LWFuZC1zb2xvL3Byb3RvLWRlZmluaXRpb25zL19nZW5lcmF0ZWQvc2VydmljZXMvbGlzdKICA0xYWKoCBExpc3TKAgVMaXN0X+ICEUxpc3RfXEdQQk1ldGFkYXRh6gIETGlzdGIGcHJvdG8z", [file_base_lists, file_base_empty]);

/**
 * @generated from message list.AssignListsRequest
 */
export type AssignListsRequest = Message<"list.AssignListsRequest"> & {
  /**
   * @generated from field: repeated list.ListAssignment listAssignments = 1;
   */
  listAssignments: ListAssignment[];
};

/**
 * Describes the message list.AssignListsRequest.
 * Use `create(AssignListsRequestSchema)` to create a new message.
 */
export const AssignListsRequestSchema: GenMessage<AssignListsRequest> = /*@__PURE__*/
  messageDesc(file_services_list_list, 0);

/**
 * @generated from message list.ListAssignment
 */
export type ListAssignment = Message<"list.ListAssignment"> & {
  /**
   * @generated from field: string mac = 1;
   */
  mac: string;

  /**
   * @generated from field: base.UserList list = 2;
   */
  list: UserList;
};

/**
 * Describes the message list.ListAssignment.
 * Use `create(ListAssignmentSchema)` to create a new message.
 */
export const ListAssignmentSchema: GenMessage<ListAssignment> = /*@__PURE__*/
  messageDesc(file_services_list_list, 1);

/**
 * @generated from service list.ListService
 */
export const ListService: GenService<{
  /**
   * @generated from rpc list.ListService.AssignList
   */
  assignList: {
    methodKind: "unary";
    input: typeof AssignListsRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_services_list_list, 0);

