// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file services/radio/radio.proto (package radio, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "../../base/empty_pb";
import { file_base_empty } from "../../base/empty_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file services/radio/radio.proto.
 */
export const file_services_radio_radio: GenFile = /*@__PURE__*/
  fileDesc("ChpzZXJ2aWNlcy9yYWRpby9yYWRpby5wcm90bxIFcmFkaW8ifQoUQ2hhbm5lbEZyZXF1ZW5jeUluZm8SHgoEYmFuZBgBIAEoDjIQLnJhZGlvLlJhZGlvQmFuZBIPCgdjaGFubmVsGAIgASgNEhEKCWZyZXF1ZW5jeRgDIAEoDRIPCgdmcmVxTG93GAQgASgNEhAKCGZyZXFIaWdoGAUgASgNIlEKHUdldEN1cnJlbnRIb3BGcmVxdWVuY2llc1JlcGx5EjAKC2ZyZXF1ZW5jaWVzGAEgAygLMhsucmFkaW8uQ2hhbm5lbEZyZXF1ZW5jeUluZm8iLwoYU3RhcnRGcmVxdWVuY3lIb3BSZXF1ZXN0EhMKC2hvcEludGVydmFsGAIgASgNIi0KGFNldEZpeGVkRnJlcXVlbmN5UmVxdWVzdBIRCglmcmVxdWVuY3kYASABKA0iSAoWU2V0Rml4ZWRGcmVxdWVuY3lSZXBseRIuCglmcmVxdWVuY3kYASABKAsyGy5yYWRpby5DaGFubmVsRnJlcXVlbmN5SW5mbyIvChhTZXRIb3BGcmVxdWVuY2llc1JlcXVlc3QSEwoLZnJlcXVlbmNpZXMYASADKA0iOQoWU3RhcnRIb3BPbkJhbmRzUmVxdWVzdBIfCgViYW5kcxgBIAMoDjIQLnJhZGlvLlJhZGlvQmFuZCo9CglSYWRpb0JhbmQSEAoMQkFORF8yXzRfR0haEAASDgoKQkFORF81X0dIWhABEg4KCkJBTkRfNl9HSFoQAjKBAwoMUmFkaW9TZXJ2aWNlEk8KGEdldEN1cnJlbnRIb3BGcmVxdWVuY2llcxILLmJhc2UuRW1wdHkaJC5yYWRpby5HZXRDdXJyZW50SG9wRnJlcXVlbmNpZXNSZXBseSIAEkMKEVN0YXJ0RnJlcXVlbmN5SG9wEh8ucmFkaW8uU3RhcnRGcmVxdWVuY3lIb3BSZXF1ZXN0GgsuYmFzZS5FbXB0eSIAElUKEVNldEZpeGVkRnJlcXVlbmN5Eh8ucmFkaW8uU2V0Rml4ZWRGcmVxdWVuY3lSZXF1ZXN0Gh0ucmFkaW8uU2V0Rml4ZWRGcmVxdWVuY3lSZXBseSIAEkMKEVNldEhvcEZyZXF1ZW5jaWVzEh8ucmFkaW8uU2V0SG9wRnJlcXVlbmNpZXNSZXF1ZXN0GgsuYmFzZS5FbXB0eSIAEj8KD1N0YXJ0SG9wT25CYW5kcxIdLnJhZGlvLlN0YXJ0SG9wT25CYW5kc1JlcXVlc3QaCy5iYXNlLkVtcHR5IgBCrQEKCWNvbS5yYWRpb0IKUmFkaW9Qcm90b1ABWmBnaXRodWIuY29tL2hhY2todW50ZXJkZXYvcGktc2Vuc29ycy9wdXJzdWl0LWFuZC1zb2xvL3Byb3RvLWRlZmluaXRpb25zL19nZW5lcmF0ZWQvc2VydmljZXMvcmFkaW+iAgNSWFiqAgVSYWRpb8oCBVJhZGlv4gIRUmFkaW9cR1BCTWV0YWRhdGHqAgVSYWRpb2IGcHJvdG8z", [file_base_empty]);

/**
 * @generated from message radio.ChannelFrequencyInfo
 */
export type ChannelFrequencyInfo = Message<"radio.ChannelFrequencyInfo"> & {
  /**
   * @generated from field: radio.RadioBand band = 1;
   */
  band: RadioBand;

  /**
   * @generated from field: uint32 channel = 2;
   */
  channel: number;

  /**
   * @generated from field: uint32 frequency = 3;
   */
  frequency: number;

  /**
   * @generated from field: uint32 freqLow = 4;
   */
  freqLow: number;

  /**
   * @generated from field: uint32 freqHigh = 5;
   */
  freqHigh: number;
};

/**
 * Describes the message radio.ChannelFrequencyInfo.
 * Use `create(ChannelFrequencyInfoSchema)` to create a new message.
 */
export const ChannelFrequencyInfoSchema: GenMessage<ChannelFrequencyInfo> = /*@__PURE__*/
  messageDesc(file_services_radio_radio, 0);

/**
 * @generated from message radio.GetCurrentHopFrequenciesReply
 */
export type GetCurrentHopFrequenciesReply = Message<"radio.GetCurrentHopFrequenciesReply"> & {
  /**
   * @generated from field: repeated radio.ChannelFrequencyInfo frequencies = 1;
   */
  frequencies: ChannelFrequencyInfo[];
};

/**
 * Describes the message radio.GetCurrentHopFrequenciesReply.
 * Use `create(GetCurrentHopFrequenciesReplySchema)` to create a new message.
 */
export const GetCurrentHopFrequenciesReplySchema: GenMessage<GetCurrentHopFrequenciesReply> = /*@__PURE__*/
  messageDesc(file_services_radio_radio, 1);

/**
 * @generated from message radio.StartFrequencyHopRequest
 */
export type StartFrequencyHopRequest = Message<"radio.StartFrequencyHopRequest"> & {
  /**
   * @generated from field: uint32 hopInterval = 2;
   */
  hopInterval: number;
};

/**
 * Describes the message radio.StartFrequencyHopRequest.
 * Use `create(StartFrequencyHopRequestSchema)` to create a new message.
 */
export const StartFrequencyHopRequestSchema: GenMessage<StartFrequencyHopRequest> = /*@__PURE__*/
  messageDesc(file_services_radio_radio, 2);

/**
 * @generated from message radio.SetFixedFrequencyRequest
 */
export type SetFixedFrequencyRequest = Message<"radio.SetFixedFrequencyRequest"> & {
  /**
   * @generated from field: uint32 frequency = 1;
   */
  frequency: number;
};

/**
 * Describes the message radio.SetFixedFrequencyRequest.
 * Use `create(SetFixedFrequencyRequestSchema)` to create a new message.
 */
export const SetFixedFrequencyRequestSchema: GenMessage<SetFixedFrequencyRequest> = /*@__PURE__*/
  messageDesc(file_services_radio_radio, 3);

/**
 * @generated from message radio.SetFixedFrequencyReply
 */
export type SetFixedFrequencyReply = Message<"radio.SetFixedFrequencyReply"> & {
  /**
   * @generated from field: radio.ChannelFrequencyInfo frequency = 1;
   */
  frequency?: ChannelFrequencyInfo;
};

/**
 * Describes the message radio.SetFixedFrequencyReply.
 * Use `create(SetFixedFrequencyReplySchema)` to create a new message.
 */
export const SetFixedFrequencyReplySchema: GenMessage<SetFixedFrequencyReply> = /*@__PURE__*/
  messageDesc(file_services_radio_radio, 4);

/**
 * @generated from message radio.SetHopFrequenciesRequest
 */
export type SetHopFrequenciesRequest = Message<"radio.SetHopFrequenciesRequest"> & {
  /**
   * @generated from field: repeated uint32 frequencies = 1;
   */
  frequencies: number[];
};

/**
 * Describes the message radio.SetHopFrequenciesRequest.
 * Use `create(SetHopFrequenciesRequestSchema)` to create a new message.
 */
export const SetHopFrequenciesRequestSchema: GenMessage<SetHopFrequenciesRequest> = /*@__PURE__*/
  messageDesc(file_services_radio_radio, 5);

/**
 * @generated from message radio.StartHopOnBandsRequest
 */
export type StartHopOnBandsRequest = Message<"radio.StartHopOnBandsRequest"> & {
  /**
   * @generated from field: repeated radio.RadioBand bands = 1;
   */
  bands: RadioBand[];
};

/**
 * Describes the message radio.StartHopOnBandsRequest.
 * Use `create(StartHopOnBandsRequestSchema)` to create a new message.
 */
export const StartHopOnBandsRequestSchema: GenMessage<StartHopOnBandsRequest> = /*@__PURE__*/
  messageDesc(file_services_radio_radio, 6);

/**
 * @generated from enum radio.RadioBand
 */
export enum RadioBand {
  /**
   * @generated from enum value: BAND_2_4_GHZ = 0;
   */
  BAND_2_4_GHZ = 0,

  /**
   * @generated from enum value: BAND_5_GHZ = 1;
   */
  BAND_5_GHZ = 1,

  /**
   * @generated from enum value: BAND_6_GHZ = 2;
   */
  BAND_6_GHZ = 2,
}

/**
 * Describes the enum radio.RadioBand.
 */
export const RadioBandSchema: GenEnum<RadioBand> = /*@__PURE__*/
  enumDesc(file_services_radio_radio, 0);

/**
 * @generated from service radio.RadioService
 */
export const RadioService: GenService<{
  /**
   * @generated from rpc radio.RadioService.GetCurrentHopFrequencies
   */
  getCurrentHopFrequencies: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof GetCurrentHopFrequenciesReplySchema;
  },
  /**
   * @generated from rpc radio.RadioService.StartFrequencyHop
   */
  startFrequencyHop: {
    methodKind: "unary";
    input: typeof StartFrequencyHopRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc radio.RadioService.SetFixedFrequency
   */
  setFixedFrequency: {
    methodKind: "unary";
    input: typeof SetFixedFrequencyRequestSchema;
    output: typeof SetFixedFrequencyReplySchema;
  },
  /**
   * @generated from rpc radio.RadioService.SetHopFrequencies
   */
  setHopFrequencies: {
    methodKind: "unary";
    input: typeof SetHopFrequenciesRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc radio.RadioService.StartHopOnBands
   */
  startHopOnBands: {
    methodKind: "unary";
    input: typeof StartHopOnBandsRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_services_radio_radio, 0);

